### ISSUE TITLE
将源码传到linux上，执行flask run 会报错找不到模块

### ISSUE THREAD

**Issue by cainiao308** [greyli/helloflask#120]
root@ubuntu:/home/zte/sayhello/sayhello# flask db
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 478, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 316, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 209, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 89, in locate_app
    __import__(module)
ImportError: No module named sayhello

**Comment by greyli** [comment]
在项目根目录（`/zte/sayhello`）执行启动命令，不是 `/zte/sayhello/sayhello` 目录。

**Comment by cainiao308** [comment]
> 在项目根目录（`/zte/sayhello`）执行启动命令，不是 `/zte/sayhello/sayhello` 目录。

(sayhello) root@ubuntu:/home/zte/sayhello# flask run
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/root/.local/share/virtualenvs/sayhello-T1ZdphFX/local/lib/python2.7/site-packages/flask/cli.py", line 693, in _validate_key
    is_context = isinstance(cert, ssl.SSLContext)
AttributeError: 'module' object has no attribute 'SSLContext'
上级目录报错这个

**Comment by greyli** [comment]
Python 版本小于 2.7.9？

**Comment by cainiao308** [comment]
> Python 版本小于 2.7.9？

2.7.6   有解决方法吗？

**Comment by greyli** [comment]
据我所知没有，升级吧。

**Comment by cainiao308** [comment]
> 据我所知没有，升级吧。

好吧。感谢

**Comment by greyli** [comment]
不客气。

**Comment by cainiao308** [comment]
> 不客气。

如果想把项目部署到容器中，pipenv shell是在Dockerfile里写还是在启动命令中写呢

**Comment by greyli** [comment]
Dockerfile

**Comment by cainiao308** [comment]
> Dockerfile

Dockerfile写好build有如下报错，不是tty
K Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/Code-RDc31JGu
Creating a Pipfile for this project...
Launching subshell in virtual environment...
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/cli/command.py", line 390, in shell
    pypi_mirror=state.pypi_mirror,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 2184, in do_shell
    shell.fork_compat(*fork_args)
  File "/usr/lib/python2.7/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 761, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (25, 'Not a tty')

**Comment by greyli** [comment]
尝试用 `pipenv run` 来执行命令（比如 `pipenv run python app.py`），不要显式的激活虚拟环境（`pipenv shell`）。

**Comment by cainiao308** [comment]
> 尝试用 `pipenv run` 来执行命令（比如 `pipenv run python app.py`），不要显式的激活虚拟环境（`pipenv shell`）。

这样可以，但是要在起容器之前初始化数据库，要执行flask forge，但是不显示的激活环境的话怎么初始化数据库呢

**Comment by greyli** [comment]
pipenv run flask forge

**Comment by greyli** [comment]
https://zhuanlan.zhihu.com/flask

先关闭了，对于新的问题请创建新的 issue 提出。
