### ISSUE TITLE
supervisor报错

### ISSUE THREAD

**Issue by goodbad3** [greyli/helloflask#150]
日志：
2019-02-06 13:30:36,825 CRIT Supervisor running as root (no user in config file)
2019-02-06 13:30:36,825 INFO Included extra file "/etc/supervisor/conf.d/bluelog.conf" during parsing
2019-02-06 13:30:36,892 INFO RPC interface 'supervisor' initialized
2019-02-06 13:30:36,892 INFO RPC interface 'supervisor' initialized
2019-02-06 13:30:36,892 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-02-06 13:30:36,894 INFO daemonizing the supervisord process
2019-02-06 13:30:36,894 INFO supervisord started with pid 1613
2019-02-06 13:30:37,897 INFO spawned: 'bluelog' with pid 1614
2019-02-06 13:30:38,785 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:39,788 INFO spawned: 'bluelog' with pid 1627
2019-02-06 13:30:40,752 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:42,756 INFO spawned: 'bluelog' with pid 1640
2019-02-06 13:30:43,715 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:46,722 INFO spawned: 'bluelog' with pid 1653
2019-02-06 13:30:47,668 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:48,670 INFO gave up: bluelog entered FATAL state, too many start retries too quickly
2019-02-06 13:30:55,302 INFO spawned: 'bluelog' with pid 1666
2019-02-06 13:30:56,246 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:57,249 INFO spawned: 'bluelog' with pid 1679
2019-02-06 13:30:58,217 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:30:59,253 ERRO 192.168.1.114:61618 - - [06/Feb/2019:05:30:59 +0800] "GET /?message=ERROR%3A%20Process%20bluelog%3A%20spawn%20error HTTP/1.1" 200 2603
2019-02-06 13:31:00,386 INFO spawned: 'bluelog' with pid 1692
2019-02-06 13:31:01,462 INFO success: bluelog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-06 13:31:01,462 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:31:02,467 INFO spawned: 'bluelog' with pid 1705
2019-02-06 13:31:03,387 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:31:04,391 INFO spawned: 'bluelog' with pid 1718
2019-02-06 13:31:05,297 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:31:07,304 INFO spawned: 'bluelog' with pid 1731
2019-02-06 13:31:08,246 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:31:11,252 INFO spawned: 'bluelog' with pid 1744
2019-02-06 13:31:12,171 INFO exited: bluelog (exit status 1; not expected)
2019-02-06 13:31:13,173 INFO gave up: bluelog entered FATAL state, too many start retries too quickly

-----------------------------------------------------------------------------------------------------------------
**配置都是安装书上的，百度了半天都不行。
supervisor配置没有错，访问http://ip:9001成功，但访问http:ip报错。**
请求作者看看！！！

**Comment by greyli** [comment]
试试下面的命令看看输出什么：
```
sudo supervisorctl tail -5000 bluelog stderr
```

**Comment by goodbad3** [comment]
hon3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 390, in shell
    pypi_mirror=state.pypi_mirror,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2184, in do_shell
    shell.fork_compat(*fork_args)
  File "/usr/local/lib/python3.6/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 761, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (22, 'Invalid argument')
Loading .env environment variables…
Launching subshell in virtual environment…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 390, in shell
    pypi_mirror=state.pypi_mirror,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2184, in do_shell
    shell.fork_compat(*fork_args)
  File "/usr/local/lib/python3.6/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 761, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (22, 'Invalid argument')
Loading .env environment variables…
Launching subshell in virtual environment…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 390, in shell
    pypi_mirror=state.pypi_mirror,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2184, in do_shell
    shell.fork_compat(*fork_args)
  File "/usr/local/lib/python3.6/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 761, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (22, 'Invalid argument')

**Comment by goodbad3** [comment]
2019-02-07 16:27:31,460 INFO spawned: 'bluelog' with pid 1909
2019-02-07 16:27:32,405 INFO exited: bluelog (exit status 1; not expected)
2019-02-07 16:27:33,414 INFO spawned: 'bluelog' with pid 1922
2019-02-07 16:27:34,357 INFO exited: bluelog (exit status 1; not expected)
2019-02-07 16:27:35,379 ERRO 192.168.1.114:50665 - - [07/Feb/2019:08:27:35 +0800] "GET /?message=ERROR%3A%20Process%20bluelog%3A%20spawn%20error HTTP/1.1" 200 2603
2019-02-07 16:27:36,383 INFO spawned: 'bluelog' with pid 1935
2019-02-07 16:27:37,291 INFO exited: bluelog (exit status 1; not expected)
2019-02-07 16:27:40,301 INFO spawned: 'bluelog' with pid 1948
2019-02-07 16:27:41,221 INFO exited: bluelog (exit status 1; not expected)
2019-02-07 16:27:42,227 INFO gave up: bluelog entered FATAL state, too many start retries too quickly

**Comment by goodbad3** [comment]
好像突然可以访问http:ip，但是  ERROR: Process bluelog: spawn error

State | Description | Name | Action
-- | -- | -- | --
backoff | Exited too quickly (process log may have details) | bluelog | Clear Log                                                   Tail -f

**Comment by greyli** [comment]
从报错看是 Pipenv 的问题，不清楚具体原因。可以尝试升级 Pipenv 和 pip 版本，或是重新安装。

**Comment by goodbad3** [comment]
好像升级后还不形

**Comment by greyli** [comment]
先关闭了，如果问题还没解决，可以继续评论或重开。
