### ISSUE TITLE
flask mail 我有一个小问题 SMTPSenderRefused: (503, 'Error: need EHLO and AUTH first !'

### ISSUE THREAD

**Issue by 99Kies** [greyli/helloflask#184]
218.205.55.38 - - [06/Oct/2019 23:25:04] "GET /mail HTTP/1.1" 200 -
send: 'ehlo instance-v53b6cq7.novalocal\r\n'
reply: '250-smtp.qq.com\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-SIZE 73400320\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-AUTH LOGIN PLAIN\r\n'
reply: '250-AUTH=LOGIN\r\n'
reply: '250-MAILCOMPRESS\r\n'
reply: '250 8BITMIME\r\n'
reply: retcode (250); Msg: smtp.qq.com
PIPELINING
SIZE 73400320
STARTTLS
AUTH LOGIN PLAIN
AUTH=LOGIN
MAILCOMPRESS
8BITMIME
send: 'STARTTLS\r\n'
reply: '220 Ready to start TLS\r\n'
reply: retcode (220); Msg: Ready to start TLS
send: 'ehlo instance-v53b6cq7.novalocal\r\n'
reply: '250-smtp.qq.com\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-SIZE 73400320\r\n'
reply: '250-AUTH LOGIN PLAIN\r\n'
reply: '250-AUTH=LOGIN\r\n'
reply: '250-MAILCOMPRESS\r\n'
reply: '250 8BITMIME\r\n'
reply: retcode (250); Msg: smtp.qq.com
PIPELINING
SIZE 73400320
AUTH LOGIN PLAIN
AUTH=LOGIN
MAILCOMPRESS
8BITMIME
send: u'mail FROM:<1290017556@qq.com> size=340\r\n'
reply: '503 Error: need EHLO and AUTH first !\r\n'
reply: retcode (503); Msg: Error: need EHLO and AUTH first !
send: 'rset\r\n'
reply: '250 Ok\r\n'
reply: retcode (250); Msg: Ok
send: 'quit\r\n'
reply: '221 Bye\r\n'
reply: retcode (221); Msg: Bye
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kies/mail_/mail_run.py", line 24, in send_async_email
    mail.send(message)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (503, 'Error: need EHLO and AUTH first !', u'1290017556@qq.com')

这个问题只发生在服务器上(ubuntu 16.04) 我windows系统可以成功运行flask_mail 邮件篇的程序

**Comment by 99Kies** [comment]
oh, is python version issue
