### ISSUE TITLE
P156 数据库删除操作的页面index.html 错误

### ISSUE THREAD

**Issue by MiracleWong** [greyli/helloflask#68]
**注意：包括这行在内，下面斜体的为模板提示文字，可以删除掉。**

### 期望的行为

*描述发生了什么。*
页面上可以，显示书籍P157 图 5-2 显示样子
```html
        <div class="note">
            <p>{{ note.body }}</p>
            <a class='btn' href="{{ url_for('edit_note', note_id=note.id) }}">Edit</a>
            <form method="post" action="{{ url_for('delete_note', note_id=note.id) }}">
                {{ form.csrf_token }}
                {{ form.submit(class='btn') }}
            </form>
        </div>
```

### 实际情况

*描述实际发生的情况。*
builtins.TypeError
TypeError: 'UnboundField' object is not callable

```pytb
builtins.TypeError
TypeError: 'UnboundField' object is not callable

Traceback (most recent call last)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/miraclewong/github/HelloFlask/demos/database/app.py", line 72, in index
return render_template('index.html', notes=notes, form=form)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
context, ctx.app)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
rv = template.render(context)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/miraclewong/.local/share/virtualenvs/HelloFlask-F3S4PtDy/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/Users/miraclewong/github/HelloFlask/demos/database/templates/index.html", line 1, in top-level template code
{% extends 'base.html' %}
File "/Users/miraclewong/github/HelloFlask/demos/database/templates/base.html", line 29, in top-level template code
{% block content %}{% endblock %}
File "/Users/miraclewong/github/HelloFlask/demos/database/templates/index.html", line 14, in block "content"
{{ form.submit(class='btn') }}
TypeError: 'UnboundField' object is not callable
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

*个人描述*
错误出现在 {{ form.submit(class='btn') }}这一行上面。

### 环境

* Python版本：Python 3.6.4
* Flask版本：Flask 1.0.2
* 操作系统：MacOS High Sierra 10.13.6 (17G65)

**Comment by MiracleWong** [comment]
通过使用Beyond Compare 比较[HelloFlask](https://github.com/greyli/helloflask) 和自己的代码，定位到了错误。是自己粗心，把`app.py` 的` index`中的
`form = DeleteNoteForm()`写成 `form = DeleteNoteForm`，导致后面的页面`form.submit`中获取不到。

**老师可以把这个issue关闭吧**

**Comment by greyli** [comment]
好的，没关系。（使用下面的“Close Issue”或“Close and comment”按钮就可以关闭）
